gems:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - pygments.rb
#  - redcarpet
#  - albino

exclude: [".idea", ".git", "README.md", "Gemfile", "Gemfile.lock"]

url: http://blog.asamaru.net
#url: http://127.0.0.1:4000
title: 이 세상에 하나는 남기고 가자
subtitle: 내가 할 수 있는 모든 것을...
author: 유영재
simple_search: https://www.google.com/search
description: > # this means to ignore newlines until "baseurl:"
  세상에 필요한 소스코드 한줄 남기고 가자.

email: asamaru@asamaru.net
baseurl: "" # the subpath of your site, e.g. /blog/

permalink: /:year/:month/:day/:title/

#markdown: redcarpet
#highlighter: pygments
#redcarpet:
#  extensions: [
#   "no_intra_emphasis"
#   ,"fenced_code_blocks"
#   ,"autolink"
#   ,"tables"
#   ,"strikethrough"
#   ,"superscript"
#   ,"with_toc_data"
#   ,"footnotes"
#   ,"highlight"
#   ,"underline"
#   ,"quote"
#   ,"lax_spacing"
#   ,"prettify"
##   ,"html_toc"
#  ]

#markdown: kramdown
#highlighter: pygments

markdown: KramdownPygments
markdown_ext: markdown,mkd,mkdn,md
textile_ext: textile
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

#markdown: kramdown
#markdown_ext: markdown,mkd,mkdn,md
#textile_ext: textile
#kramdown:
#  syntax_highlighter: rouge
#  input: GFM
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  smart_quotes: lsquo,rsquo,ldquo,rdquo

paginate: 1
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: false

# Disqus Comments
disqus_short_name: asamaru7
#disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-65749108-2

# Facebook Like
facebook_like: true

github_username: asamaru7

feed:
  path: atom.xml

#subscribe_rss: /atom.xml
#subscribe_email: asamaru@asamaru.net

category_dir: blog/categories

# archives 생성
jekyll-archives:
  enabled:
    - categories
    - year
    - month
    - day
    - tags
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
    tag: archive-tag
    category: archive-tag
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
